import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>DaveCo</title>
        <meta name="description" content="Your premier destination for fine spirits and craft beer" />
      </head>
      <body className="font-['Helvetica'] antialiased">{children}</body>
    </html>
  );
}
